[Scia Reto](https://sciareto.org) mind map   
> __version__=`1.1`,showJumps=`true`
---

# open\-sora

## 我的目标

### 根据拍摄的视频，重构数字人， 生活场景， 各种补充资料， 

### 局限在一个屋子里面

#### 走动，表情

### 真实重建，能够实时变化，开窗， 空调打开

### 简单任务

#### 将吃屎欸 这个表情包 扩充到动漫 各种任务上，无差别，嘴型对上

#### 收集原版gif

#### 各种不同人的 嘴型 和 图片 

## 他的目标

### 文生视频
