[Scia Reto](https://sciareto.org) mind map   
> __version__=`1.1`,showJumps=`true`
---

# 视频编辑

## 目标

### 根据多模态输入， 快速编辑视频

### 语言控制， 视觉控制， 

#### 语言的信息量有限

#### 梗概， 逐步细化的过程，才是视频生成

## 视频生成综述论文

### https://arxiv\.org/pdf/2310\.10647

### 中文

#### https://zhuanlan\.zhihu\.com/p/661860981

### github

#### https://github\.com/ChenHsing/Awesome\-Video\-Diffusion\-Models?tab=readme\-ov\-file\#video\-editing

### 综述论文

#### 4 视频编辑

##### 目标

###### 视频编辑任务应满足以下标准：<br/>\(1\) 保真度（fidelity）：每一帧应在内容上与原始视频的相应帧保持一致；<br/>\(2\) 对齐度（alignment）：生成的视频应与输入的控制信息对齐；<br/>\(3\) 质量（quality）：生成的视频应在时间上保持一致且质量高。
